### ISSUE TITLE
limpca help

### ISSUE THREAD

**Issue by bgovaerts** [ManonMartin/limpca#8]
If you look to the general help of limpca package (help(limpca)), functions are missing in the list of functions.  The authors are also not correct.  I would put the whole list of functions there.  The names of some functions are also not correct.  
Here is the whole list (from our recent article)

Data exploration functions
plotDesign
Provides a graphical representation of the experimental design. It allows to visualize factor levels and check the design balancing.
plotScatter
Produces a plot describing the relationship between two columns of the outcomes matrix Y. It allows to choose colors and symbols for the levels of the design factors. Ellipses, polygons or segments can be added to group different sets of points on the graph.
plotScatterM
Produces a scatter plot matrix between the selected columns of the outcomes matrix Y choosing specific colors and symbols for up to 4 factors from the design on the upper and lower diagonals.
plotMeans
Draws, for a given response variable, a plot of the response means by levels of up to three categorical factors from the design. When the design is balanced, it allows to visualize main effects or interactions for the response of interest. For unbalanced designs, this plot must be used with caution.
plotLine
Generates the response profile of one or more observations i.e. plots of one or more rows of the outcomes matrix on the y-axis against the m response variables on the x-axis. Depending on the response type (spec- tra, gene expression...), point, line or segment plots can be used.
pcaBySvd
Operates a Principal Component Analysis on the Y outcome/response matrix by a singular value decom- position. Outputs are represented with the functions pcaScorePlot, pcaLoadingPlot and pcaScreePlot.
pcaScreePlot
Returns a bar plot of the percentage of variance explained by each Principal Component (PC) calculated by pcaBySvd.
pcaScorePlot
Produces score plots from pcaBySvd output with the same graphical options as plotScatter. This is a wrapper of plotScatter.
pcaLoading1dPlot
Plots loading vectors from pcaBySvd output with different available line types. This is a wrapper of plotLine.
pcaLoading2dPlot
Produces 2D loading plots from pcaBySvd output with the same graphical options as plotScatter. This is a wrapper of plotScatter.

Modeling and results visualization
lmpModelMatrix
Creates the model matrix X from the design matrix and the model formula.
lmpEffectMatrices
Estimates the model by OLS based on the outcomes and model matrices provided in the outputs of lmpModelMatrix function and calculates the estimated effect matrices Mˆ 0 , Mˆ 1 , ...Mˆ f and residual ma- trix Eˆ. It calculates also the type III percentage of variance explained by each effect.
lmpBootstrapTests
Tests the significance of one or a combination of the model effects using bootstrap. This function is based on the outputs of lmpEffectMatrices function.
lmpPcaEffects
Performs a PCA on each of the effect matrices from the outputs of lmpEffectMatrices. It has an option to choose the method applied: ASCA, APCA or ASCA-E. Combined effects (i.e. linear combinations of original effect matrices) can also be created and decomposed by PCA.
lmpContributions
Reports the contribution of each effect to the total variance, but also the contribution of each PC to the total variance per effect. Moreover, these contributions are summarized in a barplot.
lmpScreePlot
Provides a barplot of the percentage of variance associated to the PCs of the effect matrices ordered by importance based on the outputs of lmpContributions.
lmpScorePlot
Draws the score plots of each effect matrix provided in lmpPcaEffects outputs. As a wrapper of the plotScatter function, it allows to visualize the scores of the effect matrices for two components at a time with all the available options in plotScatter.
lmpLoading1dPlot
Plots the loading vectors for each effect matrix from the lmpPcaEffects outputs with line plots. This is a wrapper of plotLine.
lmpLoading2dPlot
Draws a 2D loading plot of each effect matrix provided in lmpPcaEffects outputs. As a wrapper of the plotScatter function, it allows the visualization of effect loading matrices for two components at a time with all options available in plotScatter.
lmpScoreScatterPlotM
Plots the scores of all model effects simultaneously in a scatterplot matrix. By default, the first PC only is kept for each model effect and, as a wrapper of plotScatterM, the choice of symbols and colors to distin- guish factor levels allows an enriched visualization of the factors’ effect on the responses.
lmpEffectPlot
Plots the ASCA scores by effect levels for a given model effect and for one PC at a time. This graph is especially appealing to interpret interactions or combined effects. This is a wrapper of plotMeans.

**Comment by ManonMartin** [comment]
I improved the documentation in limpca.Rd
"The authors are also not correct.": Should we specify the authors here? Since they are already mentioned in the DESCRIPTION file
